services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-volume:/var/www
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wp-volume:/var/www
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/myko/data/mysql
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/myko/data/www